@Api_HostAddress = http://localhost:5145

Get {{ Api_HostAddress}}/Users

###

POST {{ Api_HostAddress}}/Users
Content-Type: application/json

{
  "id": 10,
  "firstName": "test",
  "lastName": "api"
}

###
PUT {{ Api_HostAddress}}/Users
Content-Type: application/json

{
  "id": 4,
  "firstName": "Mary",
  "lastName": "Sutton"
}